# Generated by Django 2.2.11 on 2020-07-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('总部', '总部'), ('分部', '分部')], max_length=50, verbose_name='节点类型')),
                ('node_address', models.CharField(max_length=255, verbose_name='节点地址')),
                ('node_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='节点联系人')),
                ('node_signer', models.CharField(default='system', max_length=50, verbose_name='登记人')),
                ('node_remarks', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('node_signtime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
